### ISSUE TITLE
 Manual Generation of Bat Files Required after Downloading Databases

### ISSUE THREAD

**Issue by IsleZhu** [pritykinlab/guidescanpy#11]
After downloading the databases, we need to use `samtools` to generate the bai files manually in the same directory as the database files (`bam.sorted` files). This could be simplified later.

**Comment by vineetbansal** [comment]
Actually this might be a good first issue to tackle. `pysam` is the python library (already listed as a dependency for this project) which can do everything that `samtools` can do, including `samtools index`. So we may need to tweak the code a bit to make sure that we do a `pysam.index` (or whatever the command in their API is) if the index file doesn't already exist, before we try to fetch records from that file.

We can tackle that once you get more comfortable with what indexing does and what these `.bam` files are actually telling you.

**Comment by vineetbansal** [comment]
Fixed in commit e933f91e47e1c373dc2ee77aa9622d45058098a5
