### ISSUE TITLE
Order of enzymes

### ISSUE THREAD

**Issue by vineetbansal** [pritykinlab/guidescanpy#4]
The order of enzymes on all screens should be cas9/cpf1 instead of the other way around.

**Comment by vineetbansal** [comment]
We're now showing `cas9/cpf1` in all dropdowns (in that order), with the dropdown selection changed automatically if the current selection is not applicable.

This, however, is done through rather ugly (and hardcoded) code:
https://github.com/pritykinlab/guidescanpy/blob/63fc13c450f0ee130b68b8b532d2fd09045cdc69/src/guidescanpy/flask/templates/grna_design.html#LL39C28-L39C28
https://github.com/pritykinlab/guidescanpy/blob/63fc13c450f0ee130b68b8b532d2fd09045cdc69/src/guidescanpy/flask/templates/grna_sequence_search.html#L23

Which looks at the previous option only (since `cas9` is better supported than `cpf1`). This will need to be modified to work in a more general case (previous/next etc.)

**Comment by IsleZhu** [comment]
Can we only show the valid selectEnzyme options for each organism? This way we don't need to check the prev/next options constantly.

**Comment by IsleZhu** [comment]
This was fixed by adding a refreshMenu function, refreshing the enzyme menu each time the user choose an organism. Only show the valid (organism, enzyme) combination.
