### ISSUE TITLE
Create a snakemake workflow for adding new organisms across the web app

### ISSUE THREAD

**Issue by vineetbansal** [pritykinlab/guidescanpy#40]
A [snakemake](https://snakemake.readthedocs.io/en/stable/) workflow that adds a new organism/enzyme combination to the web application would serve as documentation on the steps we currently take to do this, as well as actually be put to use in the future (both for adding new databases and/or replacing old ones).

**Comment by vineetbansal** [comment]
Let's add support for something like `--organism sacCer3` to the snakemake workflow if possible.

**Comment by IsleZhu** [comment]
We need to make the data path consistent with `config.json`.
