### ISSUE TITLE
import issue - no module named guidescanpy

### ISSUE THREAD

**Issue by IsleZhu** [pritykinlab/guidescanpy#9]
When attempting to run `import guidescanpy` in guidescanpy directory, it occurs `ModuleNotFoundError: No module named 'guidescanpy'`. But if I navigate to the upper level directory, the import process works smoothly.

The `guidescanpy` should be imported successfully within the guidescanpy library.

**Note:** This issue is occurring on MacOS 13.2 with Python 3.11.

**Comment by vineetbansal** [comment]
This is a bit strange, if the `pip install` step gave no errors.

Can you verify something - does `python -c "import guidescanpy"` work if you're in a completely different folder than where you've cloned the repository (say after a`cd ~/Downloads`?) If it does, can you try `python -c "import guidescanpy as m; print(m.__path__)"` and tell me what it says?

**Comment by IsleZhu** [comment]
> This is a bit strange, if the `pip install` step gave no errors.
> 
> Can you verify something - does `python -c "import guidescanpy"` work if you're in a completely different folder than where you've cloned the repository (say after a`cd ~/Downloads`?) If it does, can you try `python -c "import guidescanpy as m; print(m.__path__)"` and tell me what it says?

No, it still has the same error.

**Comment by IsleZhu** [comment]
It's a problem with the bash file on my device. Commented out some path lines then it worked.
